import { EquipmentType } from "../schemas/equipment";

export interface SensorLimitRule {
  sensorKey: string;
  name: string;
  unit: string;
  plausibleMin: number;
  plausibleMax: number;
  normalMin?: number;
  normalMax?: number;
  warningLow?: number;
  warningHigh?: number;
  criticalLow?: number;
  criticalHigh?: number;
  isSafetyRelevant?: boolean;
  description: string;
}

export const EQUIPMENT_SENSOR_LIMITS: Record<EquipmentType, SensorLimitRule[]> = {
  centrifugal_pump: [
    {
      sensorKey: "bearing_temp_c",
      name: "Bearing Temperature",
      unit: "celsius",
      plausibleMin: -10,
      plausibleMax: 200,
      normalMin: 35,
      normalMax: 70,
      warningHigh: 75,
      criticalHigh: 85,
      isSafetyRelevant: true,
      description: "Temperature of pump inboard and outboard bearings.",
    },
    {
      sensorKey: "vibration_rms_mms",
      name: "Vibration Overall RMS",
      unit: "mm/s",
      plausibleMin: 0,
      plausibleMax: 50,
      normalMin: 0.5,
      normalMax: 3.0,
      warningHigh: 4.5,
      criticalHigh: 7.0,
      isSafetyRelevant: true,
      description: "Overall radial vibration velocity on pump bearing housing.",
    },
    {
      sensorKey: "discharge_pressure_psi",
      name: "Discharge Pressure",
      unit: "psi",
      plausibleMin: 0,
      plausibleMax: 350,
      normalMin: 60,
      normalMax: 120,
      warningLow: 50,
      warningHigh: 135,
      criticalLow: 35,
      criticalHigh: 150,
      isSafetyRelevant: true,
      description: "Fluid pressure at pump discharge flange.",
    },
    {
      sensorKey: "suction_pressure_psi",
      name: "Suction Pressure",
      unit: "psi",
      plausibleMin: -15,
      plausibleMax: 100,
      normalMin: 10,
      normalMax: 30,
      warningLow: 5,
      criticalLow: 2,
      isSafetyRelevant: true,
      description: "Net positive inlet pressure (cavitation threshold).",
    },
    {
      sensorKey: "motor_current_amps",
      name: "Motor Current",
      unit: "amps",
      plausibleMin: 0,
      plausibleMax: 150,
      normalMin: 15,
      normalMax: 40,
      warningHigh: 45,
      criticalHigh: 52,
      description: "Electrical current draw of drive motor.",
    },
    {
      sensorKey: "seal_leakage_flow_mlpm",
      name: "Mechanical Seal Leakage",
      unit: "ml/min",
      plausibleMin: 0,
      plausibleMax: 1000,
      normalMin: 0,
      normalMax: 5,
      warningHigh: 15,
      criticalHigh: 50,
      isSafetyRelevant: true,
      description: "Drain flow from mechanical seal gland catch basin.",
    },
  ],

  air_compressor: [
    {
      sensorKey: "discharge_temp_c",
      name: "Air Discharge Temperature",
      unit: "celsius",
      plausibleMin: -10,
      plausibleMax: 250,
      normalMin: 70,
      normalMax: 95,
      warningHigh: 100,
      criticalHigh: 110,
      isSafetyRelevant: true,
      description: "Compressed air temperature exiting airend compression chamber.",
    },
    {
      sensorKey: "discharge_pressure_psi",
      name: "Discharge Pressure",
      unit: "psi",
      plausibleMin: 0,
      plausibleMax: 300,
      normalMin: 90,
      normalMax: 125,
      warningHigh: 135,
      criticalHigh: 150,
      isSafetyRelevant: true,
      description: "Receiver tank / distribution manifold pressure.",
    },
    {
      sensorKey: "oil_pressure_psi",
      name: "Lube Oil Pressure",
      unit: "psi",
      plausibleMin: 0,
      plausibleMax: 120,
      normalMin: 25,
      normalMax: 50,
      warningLow: 20,
      criticalLow: 15,
      isSafetyRelevant: true,
      description: "Lubrication circuit pressure across filters and bearings.",
    },
    {
      sensorKey: "oil_temp_c",
      name: "Lube Oil Temperature",
      unit: "celsius",
      plausibleMin: -10,
      plausibleMax: 200,
      normalMin: 50,
      normalMax: 75,
      warningHigh: 80,
      criticalHigh: 90,
      isSafetyRelevant: true,
      description: "Oil sump temperature before thermostatic cooler valve.",
    },
    {
      sensorKey: "vibration_rms_mms",
      name: "Airend Vibration RMS",
      unit: "mm/s",
      plausibleMin: 0,
      plausibleMax: 50,
      normalMin: 0.5,
      normalMax: 2.8,
      warningHigh: 4.0,
      criticalHigh: 6.5,
      isSafetyRelevant: true,
      description: "Screw airend casing radial vibration.",
    },
    {
      sensorKey: "motor_current_amps",
      name: "Drive Motor Current",
      unit: "amps",
      plausibleMin: 0,
      plausibleMax: 200,
      normalMin: 25,
      normalMax: 60,
      warningHigh: 68,
      criticalHigh: 78,
      description: "Main motor electrical load under full compression cycle.",
    },
  ],

  hvac_chiller: [
    {
      sensorKey: "evaporator_temp_c",
      name: "Chilled Water Leaving Temp",
      unit: "celsius",
      plausibleMin: -30,
      plausibleMax: 50,
      normalMin: 4,
      normalMax: 8,
      warningLow: 2,
      criticalLow: 0,
      isSafetyRelevant: true,
      description: "Supply water temperature exiting evaporator (anti-freeze boundary).",
    },
    {
      sensorKey: "condenser_temp_c",
      name: "Condenser Leaving Water Temp",
      unit: "celsius",
      plausibleMin: 0,
      plausibleMax: 80,
      normalMin: 28,
      normalMax: 38,
      warningHigh: 43,
      criticalHigh: 48,
      isSafetyRelevant: true,
      description: "Cooling tower water exiting refrigerant condenser shell.",
    },
    {
      sensorKey: "evaporator_pressure_psi",
      name: "Evaporator Suction Pressure",
      unit: "psi",
      plausibleMin: 0,
      plausibleMax: 150,
      normalMin: 35,
      normalMax: 50,
      warningLow: 30,
      criticalLow: 22,
      isSafetyRelevant: true,
      description: "Refrigerant suction pressure entering centrifugal/screw compressor.",
    },
    {
      sensorKey: "condenser_pressure_psi",
      name: "Condenser Head Pressure",
      unit: "psi",
      plausibleMin: 0,
      plausibleMax: 450,
      normalMin: 120,
      normalMax: 180,
      warningHigh: 200,
      criticalHigh: 230,
      isSafetyRelevant: true,
      description: "High side refrigerant pressure across condenser coil.",
    },
    {
      sensorKey: "compressor_vibration_rms_mms",
      name: "Compressor Vibration",
      unit: "mm/s",
      plausibleMin: 0,
      plausibleMax: 40,
      normalMin: 0.5,
      normalMax: 2.5,
      warningHigh: 3.8,
      criticalHigh: 5.5,
      isSafetyRelevant: true,
      description: "RMS vibration on compressor mounting feet and bearing housing.",
    },
    {
      sensorKey: "motor_current_amps",
      name: "Compressor Motor Current",
      unit: "amps",
      plausibleMin: 0,
      plausibleMax: 300,
      normalMin: 40,
      normalMax: 90,
      warningHigh: 105,
      criticalHigh: 120,
      description: "Current draw of compressor semi-hermetic motor.",
    },
  ],

  electric_motor: [
    {
      sensorKey: "winding_temp_c",
      name: "Stator Winding Temperature",
      unit: "celsius",
      plausibleMin: -20,
      plausibleMax: 260,
      normalMin: 50,
      normalMax: 95,
      warningHigh: 110,
      criticalHigh: 130,
      isSafetyRelevant: true,
      description: "Internal RTD/thermocouple temperature of motor stator coils (Class F limit).",
    },
    {
      sensorKey: "bearing_de_temp_c",
      name: "Drive End (DE) Bearing Temp",
      unit: "celsius",
      plausibleMin: -20,
      plausibleMax: 200,
      normalMin: 40,
      normalMax: 75,
      warningHigh: 85,
      criticalHigh: 95,
      isSafetyRelevant: true,
      description: "Temperature of front shaft output bearing.",
    },
    {
      sensorKey: "bearing_nde_temp_c",
      name: "Non-Drive End (NDE) Bearing Temp",
      unit: "celsius",
      plausibleMin: -20,
      plausibleMax: 200,
      normalMin: 35,
      normalMax: 70,
      warningHigh: 80,
      criticalHigh: 90,
      isSafetyRelevant: true,
      description: "Temperature of rear cooling fan side bearing.",
    },
    {
      sensorKey: "vibration_rms_mms",
      name: "Overall Vibration RMS",
      unit: "mm/s",
      plausibleMin: 0,
      plausibleMax: 50,
      normalMin: 0.4,
      normalMax: 2.5,
      warningHigh: 3.5,
      criticalHigh: 5.5,
      isSafetyRelevant: true,
      description: "Radial vibration according to ISO 10816-3 criteria.",
    },
    {
      sensorKey: "current_draw_amps",
      name: "Phase Current (Average)",
      unit: "amps",
      plausibleMin: 0,
      plausibleMax: 200,
      normalMin: 10,
      normalMax: 50,
      warningHigh: 55,
      criticalHigh: 65,
      description: "Full load electrical current drawn from three-phase supply.",
    },
    {
      sensorKey: "current_unbalance_pct",
      name: "Current Phase Unbalance",
      unit: "percent",
      plausibleMin: 0,
      plausibleMax: 100,
      normalMin: 0,
      normalMax: 3,
      warningHigh: 5,
      criticalHigh: 10,
      isSafetyRelevant: true,
      description: "Maximum percentage deviation between three line currents.",
    },
  ],

  conveyor: [
    {
      sensorKey: "belt_speed_mps",
      name: "Belt Linear Velocity",
      unit: "m/s",
      plausibleMin: 0,
      plausibleMax: 10,
      normalMin: 1.2,
      normalMax: 2.5,
      warningLow: 1.0,
      warningHigh: 2.8,
      criticalLow: 0.5,
      criticalHigh: 3.2,
      isSafetyRelevant: true,
      description: "Tachometer surface velocity of conveyor transport belt.",
    },
    {
      sensorKey: "drive_pulley_temp_c",
      name: "Head Drive Pulley Bearing Temp",
      unit: "celsius",
      plausibleMin: -20,
      plausibleMax: 200,
      normalMin: 30,
      normalMax: 65,
      warningHigh: 75,
      criticalHigh: 90,
      isSafetyRelevant: true,
      description: "Pillow block bearing temperature at primary drive drum.",
    },
    {
      sensorKey: "tail_pulley_temp_c",
      name: "Tail Pulley Bearing Temp",
      unit: "celsius",
      plausibleMin: -20,
      plausibleMax: 200,
      normalMin: 25,
      normalMax: 60,
      warningHigh: 70,
      criticalHigh: 85,
      isSafetyRelevant: true,
      description: "Pillow block bearing temperature at take-up/tail drum.",
    },
    {
      sensorKey: "motor_current_amps",
      name: "Drive Motor Current",
      unit: "amps",
      plausibleMin: 0,
      plausibleMax: 150,
      normalMin: 15,
      normalMax: 35,
      warningHigh: 40,
      criticalHigh: 48,
      description: "Current draw of shaft-mounted helical gearmotor.",
    },
    {
      sensorKey: "gearbox_vibration_rms_mms",
      name: "Gearbox Vibration RMS",
      unit: "mm/s",
      plausibleMin: 0,
      plausibleMax: 50,
      normalMin: 0.5,
      normalMax: 3.0,
      warningHigh: 4.5,
      criticalHigh: 7.0,
      isSafetyRelevant: true,
      description: "Triaxial casing vibration on speed reducer housing.",
    },
    {
      sensorKey: "belt_misalignment_mm",
      name: "Belt Edge Lateral Drift",
      unit: "mm",
      plausibleMin: 0,
      plausibleMax: 200,
      normalMin: 0,
      normalMax: 10,
      warningHigh: 20,
      criticalHigh: 35,
      isSafetyRelevant: true,
      description: "Lateral tracking deviation from conveyor center line.",
    },
  ],
};

/**
 * Single source of truth lookup for equipment sensor limits.
 */
export function getSensorLimit(
  equipmentType: EquipmentType,
  sensorKey: string
): SensorLimitRule | undefined {
  const limits = EQUIPMENT_SENSOR_LIMITS[equipmentType];
  return limits?.find((l) => l.sensorKey === sensorKey);
}
