/**
 * Gemini-compatible JSON schema definition for AiTriageOutput.
 * Used as responseSchema in @google/genai structured outputs.
 */

const CitationSchema = {
  type: "OBJECT",
  description: "Verifiable citation pointing to a knowledge chunk, event index, or sensor key.",
  properties: {
    type: {
      type: "STRING",
      enum: ["kb", "event", "sensor"],
    },
    chunkId: {
      type: "STRING",
      description: "Knowledge base chunk identifier (required for type='kb').",
    },
    quote: {
      type: "STRING",
      description: "Optional verbatim quote from cited chunk.",
    },
    eventIndex: {
      type: "INTEGER",
      description: "0-based event index in recent operating events (required for type='event').",
    },
    key: {
      type: "STRING",
      description: "Sensor key string (required for type='sensor').",
    },
  },
  required: ["type"],
};

export const GEMINI_TRIAGE_RESPONSE_SCHEMA = {
  type: "OBJECT",
  description: "Structured triage recommendations generated by the AI assistant.",
  properties: {
    observations: {
      type: "ARRAY",
      description: "Observations synthesized from telemetry, events, and rule findings.",
      items: {
        type: "OBJECT",
        properties: {
          text: { type: "STRING" },
          citations: {
            type: "ARRAY",
            items: CitationSchema,
          },
        },
        required: ["text", "citations"],
      },
    },
    possibleCauses: {
      type: "ARRAY",
      description: "Hypothetical candidate causes framed probabilistically.",
      items: {
        type: "OBJECT",
        properties: {
          hypothesis: { type: "STRING" },
          likelihood: {
            type: "STRING",
            enum: ["low", "medium", "high"],
          },
          citations: {
            type: "ARRAY",
            items: CitationSchema,
          },
        },
        required: ["hypothesis", "likelihood", "citations"],
      },
    },
    followUpQuestions: {
      type: "ARRAY",
      description: "Targeted follow-up diagnostic questions (max 5) to resolve ambiguities.",
      items: {
        type: "OBJECT",
        properties: {
          question: { type: "STRING" },
          whyItMatters: { type: "STRING" },
          citations: {
            type: "ARRAY",
            items: CitationSchema,
          },
        },
        required: ["question", "whyItMatters", "citations"],
      },
    },
    inspectionSteps: {
      type: "ARRAY",
      description: "Sequential physical inspection procedures referenced from manuals.",
      items: {
        type: "OBJECT",
        properties: {
          order: { type: "INTEGER" },
          instruction: { type: "STRING" },
          safetyNote: { type: "STRING" },
          citations: {
            type: "ARRAY",
            items: CitationSchema,
          },
        },
        required: ["order", "instruction", "citations"],
      },
    },
    suggestedPriority: {
      type: "STRING",
      enum: ["low", "medium", "high", "critical"],
      description: "AI-suggested priority level.",
    },
    priorityRationale: {
      type: "OBJECT",
      description: "Evidence-based justification for suggested priority.",
      properties: {
        text: { type: "STRING" },
        citations: {
          type: "ARRAY",
          items: CitationSchema,
        },
      },
      required: ["text", "citations"],
    },
    draftWorkOrder: {
      type: "OBJECT",
      description: "Preliminary draft work order for human technician review.",
      properties: {
        title: { type: "STRING" },
        description: { type: "STRING" },
        recommendedActions: {
          type: "ARRAY",
          items: { type: "STRING" },
        },
        partsToCheck: {
          type: "ARRAY",
          items: { type: "STRING" },
        },
      },
      required: ["title", "description", "recommendedActions", "partsToCheck"],
    },
    uncertaintyNotes: {
      type: "ARRAY",
      description: "Explicit gaps in manuals, missing sensors, or unconfirmed symptoms.",
      items: { type: "STRING" },
    },
  },
  required: [
    "observations",
    "possibleCauses",
    "followUpQuestions",
    "inspectionSteps",
    "suggestedPriority",
    "priorityRationale",
    "draftWorkOrder",
    "uncertaintyNotes",
  ],
};
