import { z } from "zod";
import { CitationSchema } from "./citation";
import { PriorityLevelSchema } from "./priority";

export const AiLikelihoodSchema = z.enum(["low", "medium", "high"]);
export type AiLikelihood = z.infer<typeof AiLikelihoodSchema>;

/**
 * Structured observation made from user report, sensor telemetry, or operating events.
 */
export const AiObservationSchema = z.object({
  text: z.string().trim().min(1, "Observation text cannot be empty"),
  citations: z.array(CitationSchema).default([]),
});
export type AiObservation = z.infer<typeof AiObservationSchema>;

/**
 * Possible cause hypothesis.
 * Non-negotiable rule 3: Possible causes are always labelled as hypotheses.
 * 'Confirmed findings' can only be entered by a human technician;
 * explicit 'isConfirmed' or confirmed cause fields are strictly forbidden.
 */
export const AiPossibleCauseSchema = z
  .object({
    hypothesis: z.string().trim().min(1, "Hypothesis text cannot be empty"),
    likelihood: AiLikelihoodSchema,
    citations: z.array(CitationSchema).default([]),
  })
  .strict();

export type AiPossibleCause = z.infer<typeof AiPossibleCauseSchema>;

/**
 * Follow-up diagnostic question suggested to pinpoint equipment status.
 */
export const AiFollowUpQuestionSchema = z.object({
  question: z.string().trim().min(1, "Question cannot be empty"),
  whyItMatters: z.string().trim().min(1, "Reasoning cannot be empty"),
  citations: z.array(CitationSchema).default([]),
});
export type AiFollowUpQuestion = z.infer<typeof AiFollowUpQuestionSchema>;

/**
 * Ordered physical inspection step with optional safety warnings.
 */
export const AiInspectionStepSchema = z.object({
  order: z.number().int().positive("Inspection order must be a positive integer"),
  instruction: z.string().trim().min(1, "Instruction cannot be empty"),
  safetyNote: z.string().trim().optional(),
  citations: z.array(CitationSchema).default([]),
});
export type AiInspectionStep = z.infer<typeof AiInspectionStepSchema>;

/**
 * Suggested priority rationale with citations.
 */
export const AiPriorityRationaleSchema = z.object({
  text: z.string().trim().min(1, "Rationale text cannot be empty"),
  citations: z.array(CitationSchema).default([]),
});
export type AiPriorityRationale = z.infer<typeof AiPriorityRationaleSchema>;

/**
 * Draft work order generated by AI triage for technician review.
 */
export const AiDraftWorkOrderSchema = z.object({
  title: z.string().trim().min(1, "Work order title cannot be empty"),
  description: z.string().trim().min(1, "Work order description cannot be empty"),
  recommendedActions: z.array(z.string().trim().min(1)),
  partsToCheck: z.array(z.string().trim().min(1)),
});
export type AiDraftWorkOrder = z.infer<typeof AiDraftWorkOrderSchema>;

/**
 * Keys strictly disallowed in AI triage output to prevent LLM from hallucinating or recording confirmed findings.
 */
const FORBIDDEN_CONFIRMED_KEYS = [
  "isconfirmed",
  "is_confirmed",
  "confirmed",
  "confirmedfinding",
  "confirmedfindings",
  "confirmedcause",
  "confirmedcauses",
];

function checkForForbiddenConfirmedFields(data: unknown, ctx: z.RefinementCtx) {
  if (!data || typeof data !== "object") return;

  for (const [key, value] of Object.entries(data as Record<string, unknown>)) {
    const normalizedKey = key.toLowerCase().replace(/[-_]/g, "");
    if (FORBIDDEN_CONFIRMED_KEYS.includes(normalizedKey)) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message: `Forbidden field '${key}' detected. Non-negotiable rule 3: AI output must not contain confirmed cause or findings fields. Only human technicians can record confirmed findings.`,
        path: [key],
      });
    }

    if (Array.isArray(value)) {
      value.forEach((item, index) => {
        if (item && typeof item === "object") {
          for (const itemKey of Object.keys(item as Record<string, unknown>)) {
            const normalizedItemKey = itemKey.toLowerCase().replace(/[-_]/g, "");
            if (FORBIDDEN_CONFIRMED_KEYS.includes(normalizedItemKey)) {
              ctx.addIssue({
                code: z.ZodIssueCode.custom,
                message: `Forbidden field '${itemKey}' detected in array at index ${index}. Non-negotiable rule 3: AI output must not contain confirmed cause or findings fields.`,
                path: [key, index, itemKey],
              });
            }
          }
        }
      });
    }
  }
}

/**
 * Exact schema sent to Gemini as responseSchema and used to parse its reply.
 */
export const AiTriageOutputSchema = z
  .object({
    observations: z.array(AiObservationSchema),
    possibleCauses: z.array(AiPossibleCauseSchema),
    followUpQuestions: z.array(AiFollowUpQuestionSchema),
    inspectionSteps: z.array(AiInspectionStepSchema),
    suggestedPriority: PriorityLevelSchema,
    priorityRationale: AiPriorityRationaleSchema,
    draftWorkOrder: AiDraftWorkOrderSchema,
    uncertaintyNotes: z.array(z.string().trim()),
  })
  .strict()
  .superRefine((data, ctx) => {
    checkForForbiddenConfirmedFields(data, ctx);
  });

export type AiTriageOutput = z.infer<typeof AiTriageOutputSchema>;
